---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
meteorologia
<!-- badges: start -->

<!-- badges: end -->

El objetivo de este paquete es analizar datos de estaciones meteorologicas, resumirlos y presentarlos de manera clara.

Instalacion

Se puede instalar el paquete directamente desde GitHub
 con:
   
  # install.packages("pak")
pak::pak("biancarossi/meteorologia")

Carga del paquete

Para usar el paquete, cargarlo con:
library(meteorologia)

Funciones principales

El paquete incluye tres funciones principales:

1. leer_datos_estacion()

Descarga y lee los datos meteorologicos de una estacion especifica del INTA.
estacion1 <- leer_datos_estacion("NH0910", "inst/extdata/estacionNH0910.csv")


2. tabla_resumen_temperatura()

Crea una tabla resumen con estadisticas basicas de temperatura: promedio, desvio estandar, temperatura maxima y minima.

tabla_resumen_temperatura(estacion1)

3. grafico_temperatura_mensual()

Genera un grafico de lineas con la temperatura promedio mensual de una o varias estaciones.

grafico_temperatura_mensual(estacion1, c("purple"), "Temperatura promedio mensual")

Creditos

Datos meteorologicos obtenidos del Instituto Nacional de Tecnologia Agropecuaria (INTA) – Sistema de Informacion y Gestion Agropecuaria (SIGA).

Autores

Bianca Rossi y Liz Emilia Martinez

Licencia

MIT © Bianca Rossi


